apiVersion: v1
kind: Service
metadata:
  name: sm-service
spec:
  type: NodePort
  selector:
    app: solemates
  ports:
    - name: solemates
      protocol: TCP
      port: 4000
      targetPort: 4000
  

